### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by zlukenic** [edissyum/opencaptureforinvoices#208]
Hello, we try to install OpenCapture for Invoices but at the end we have a problem.
During install everything is ok. But at the end, on the login page, before i enter any thing i have :

**http://XXX.XXX.XXX.XXX/backend_oc/ws/auth/getEnabledLoginMethod 500 : Internal Server Error**

I try to installa the 2.2.4 version but same thing. At the end i have a login page and when i try to login as admin / admin i have the message:

**http://XXX.XXX.XXX.XXX/backend_oc/ws/auth/login Erreur lors de la connexion à la basae de donnée: invalid dsn; invalid connection option""**

both serveur are on ProxMoxVe 7.1-12 with 2GB ram, 2 vcpu, virtio SCSI 20G hdd and Ubuntu 22

**Comment by zlukenic** [comment]
i found this:
**sudo tail -f /var/www/html/opencaptureforinvoices/bin/data/log/OCforInvoices.log
[Open-Capture] [Database.py line 44 ] 08-08-2022 22:52:29 ERROR PGSQL connection error : invalid dsn: invalid connection option ""**

i listed postres database and i think that is the problem:
=====================
postgres=# \l
                                  List of databases
   Name    |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges
-----------+----------+----------+-------------+-------------+-----------------------
 postgres  | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
 template0 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
           |          |          |             |             | postgres=CTc/postgres
(3 rows)

=====================

**Comment by nathan30** [comment]
Hi,

For now the installation documentation is ready for the next version (2.4.0), sorry for that. This is why you don't have any database. The tag has to be released today or tomorrow. You could start to play with it using the dev_nch branch and follow the installation instructions on the official documentation
