### ISSUE TITLE
[BUG] 502 Bad Gateway

### ISSUE THREAD

**Issue by alexp43** [edissyum/opencaptureforinvoices#24]
Hello,

**Describe the bug**
When I upload a file, I have the error "502 Bad Gatway"

**To Reproduce**
I followed the readme but I had a problem for the installation. I had to modify the requierement for the python3 line (I removed the version)

** Installation informations (please complete the following information):**
 - OS: Ubuntu 20.04 on Proxmox

How can I solve the problem?
Thanks

**Comment by nathan30** [comment]
Hi,

Could you send me the return for : 

`sudo systemctl status OCForInvoices-web`
`sudo systemctl status OCForInvoices-worker`

**Comment by alexp43** [comment]
Hi, 
sudo systemctl status OCForInvoices-web
Active

sudo systemctl status OCForInvoices-worker
Failed

After sudo systemctl restart OCForInvoices-worker the status is active for 2-3 secondes and after it's failed

**Comment by nathan30** [comment]
Please give me the return of the command that fail

**Comment by alexp43** [comment]
alex@alex:~$ sudo systemctl status OCForInvoices-web
● OCForInvoices-web.service - Gunicorn instance to Open-Capture For Invoices
     Loaded: loaded (/etc/systemd/system/OCForInvoices-web.service; enabled; ve>
     Active: active (running) since Fri 2020-11-06 10:45:43 CET; 23min ago
   Main PID: 15897 (gunicorn)
      Tasks: 4 (limit: 18695)
     Memory: 209.3M
     CGroup: /system.slice/OCForInvoices-web.service
             ├─15897 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 >
             ├─15946 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 >
             ├─15947 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 >
             └─15950 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 >

nov. 06 10:45:43 alex-Maarch systemd[1]: Started Gunicorn instance to Open-Capt>
nov. 06 10:45:43 alex-Maarch gunicorn[15897]: [2020-11-06 10:45:43 +0100] [1589>
nov. 06 10:45:43 alex-Maarch gunicorn[15897]: [2020-11-06 10:45:43 +0100] [1589>
nov. 06 10:45:43 alex-Maarch gunicorn[15897]: [2020-11-06 10:45:43 +0100] [1589>
nov. 06 10:45:43 alex-Maarch gunicorn[15946]: [2020-11-06 10:45:43 +0100] [1594>
nov. 06 10:45:43 alex-Maarch gunicorn[15947]: [2020-11-06 10:45:43 +0100] [1594>
nov. 06 10:45:43 alex-Maarch gunicorn[15950]: [2020-11-06 10:45:43 +0100] [1595>

alex@alex:~$ sudo systemctl status OCForInvoices-worker
● OCForInvoices-worker.service - Daemon for Open-Capture for Invoices
     Loaded: loaded (/etc/systemd/system/OCForInvoices-worker.service; enabled;>
     Active: failed (Result: exit-code) since Fri 2020-11-06 10:45:51 CET; 23mi>
   Main PID: 16868 (code=exited, status=132)

nov. 06 10:45:51 alex-Maarch systemd[1]: OCForInvoices-worker.service: Schedule>
nov. 06 10:45:51 alex-Maarch systemd[1]: Stopped Daemon for Open-Capture for In>
nov. 06 10:45:51 alex-Maarch systemd[1]: OCForInvoices-worker.service: Start re>
nov. 06 10:45:51 alex-Maarch systemd[1]: OCForInvoices-worker.service: Failed w>
nov. 06 10:45:51 alex-Maarch systemd[1]: Failed to start Daemon for Open-Captur>

alex@alex:~$ sudo systemctl restart  OCForInvoices-worker
alex@alex:~$ sudo systemctl status OCForInvoices-worker
● OCForInvoices-worker.service - Daemon for Open-Capture for Invoices
     Loaded: loaded (/etc/systemd/system/OCForInvoices-worker.service; enabled;>
     Active: active (running) since Fri 2020-11-06 11:10:39 CET; 404ms ago
   Main PID: 19820 (service_workerO)
      Tasks: 9 (limit: 18695)
     Memory: 36.5M
     CGroup: /system.slice/OCForInvoices-worker.service
             ├─19820 /bin/bash /opt/OpenCaptureForInvoices/bin/scripts/service_>
             └─19821 /usr/bin/python3 /usr/local/bin/kuyruk --app bin.src.main.>

nov. 06 11:10:39 alex-Maarch systemd[1]: Started Daemon for Open-Capture for In>

alex@alex:~$ sudo systemctl status OCForInvoices-worker
● OCForInvoices-worker.service - Daemon for Open-Capture for Invoices
     Loaded: loaded (/etc/systemd/system/OCForInvoices-worker.service; enabled;>
     Active: failed (Result: exit-code) since Fri 2020-11-06 11:10:45 CET; 37s >
    Process: 20056 ExecStart=/opt/OpenCaptureForInvoices//bin/scripts/service_w>
   Main PID: 20056 (code=exited, status=132)

nov. 06 11:10:45 alex-Maarch systemd[1]: OCForInvoices-worker.service: Schedule>
nov. 06 11:10:45 alex-Maarch systemd[1]: Stopped Daemon for Open-Capture for In>
nov. 06 11:10:45 alex-Maarch systemd[1]: OCForInvoices-worker.service: Start re>
nov. 06 11:10:45 alex-Maarch systemd[1]: OCForInvoices-worker.service: Failed w>
nov. 06 11:10:45 alex-Maarch systemd[1]: Failed to start Daemon for Open-Captur>
lines 1-11/11 (END)

**Comment by alexp43** [comment]
alex-Maarch:~$ sudo systemctl status OCForInvoices-web
● OCForInvoices-web.service - Gunicorn instance to Open-Capture For Invoices
     Loaded: loaded (/etc/systemd/system/OCForInvoices-web.service; enabled; ve>
     Active: active (running) since Fri 2020-11-06 10:45:43 CET; 23min ago
   Main PID: 15897 (gunicorn)
      Tasks: 4 (limit: 18695)
     Memory: 209.3M
     CGroup: /system.slice/OCForInvoices-web.service
             ├─15897 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 >
             ├─15946 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 >
             ├─15947 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 >
             └─15950 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 >

nov. 06 10:45:43 alex-Maarch systemd[1]: Started Gunicorn instance to Open-Capt>
nov. 06 10:45:43 alex-Maarch gunicorn[15897]: [2020-11-06 10:45:43 +0100] [1589>
nov. 06 10:45:43 alex-Maarch gunicorn[15897]: [2020-11-06 10:45:43 +0100] [1589>
nov. 06 10:45:43 alex-Maarch gunicorn[15897]: [2020-11-06 10:45:43 +0100] [1589>
nov. 06 10:45:43 alex-Maarch gunicorn[15946]: [2020-11-06 10:45:43 +0100] [1594>
nov. 06 10:45:43 alex-Maarch gunicorn[15947]: [2020-11-06 10:45:43 +0100] [1594>
nov. 06 10:45:43 alex-Maarch gunicorn[15950]: [2020-11-06 10:45:43 +0100] [1595>

alex@alex-Maarch:~$ sudo systemctl status OCForInvoices-worker
● OCForInvoices-worker.service - Daemon for Open-Capture for Invoices
     Loaded: loaded (/etc/systemd/system/OCForInvoices-worker.service; enabled;>
     Active: failed (Result: exit-code) since Fri 2020-11-06 10:45:51 CET; 23mi>
   Main PID: 16868 (code=exited, status=132)

nov. 06 10:45:51 alex-Maarch systemd[1]: OCForInvoices-worker.service: Schedule>
nov. 06 10:45:51 alex-Maarch systemd[1]: Stopped Daemon for Open-Capture for In>
nov. 06 10:45:51 alex-Maarch systemd[1]: OCForInvoices-worker.service: Start re>
nov. 06 10:45:51 alex-Maarch systemd[1]: OCForInvoices-worker.service: Failed w>
nov. 06 10:45:51 alex-Maarch systemd[1]: Failed to start Daemon for Open-Captur>

alex@alex-Maarch:~$ sudo systemctl restart  OCForInvoices-worker
alex@alex-Maarch:~$ sudo systemctl status OCForInvoices-worker
● OCForInvoices-worker.service - Daemon for Open-Capture for Invoices
     Loaded: loaded (/etc/systemd/system/OCForInvoices-worker.service; enabled;>
     Active: active (running) since Fri 2020-11-06 11:10:39 CET; 404ms ago
   Main PID: 19820 (service_workerO)
      Tasks: 9 (limit: 18695)
     Memory: 36.5M
     CGroup: /system.slice/OCForInvoices-worker.service
             ├─19820 /bin/bash /opt/OpenCaptureForInvoices/bin/scripts/service_>
             └─19821 /usr/bin/python3 /usr/local/bin/kuyruk --app bin.src.main.>

nov. 06 11:10:39 alex-Maarch systemd[1]: Started Daemon for Open-Capture for In>

alex@alex-Maarch:~$ sudo systemctl status OCForInvoices-worker
● OCForInvoices-worker.service - Daemon for Open-Capture for Invoices
     Loaded: loaded (/etc/systemd/system/OCForInvoices-worker.service; enabled;>
     Active: failed (Result: exit-code) since Fri 2020-11-06 11:10:45 CET; 37s >
    Process: 20056 ExecStart=/opt/OpenCaptureForInvoices//bin/scripts/service_w>
   Main PID: 20056 (code=exited, status=132)

nov. 06 11:10:45 alex-Maarch systemd[1]: OCForInvoices-worker.service: Schedule>
nov. 06 11:10:45 alex-Maarch systemd[1]: Stopped Daemon for Open-Capture for In>
nov. 06 11:10:45 alex-Maarch systemd[1]: OCForInvoices-worker.service: Start re>
nov. 06 11:10:45 alex-Maarch systemd[1]: OCForInvoices-worker.service: Failed w>
nov. 06 11:10:45 alex-Maarch systemd[1]: Failed to start Daemon for Open-Captur>
lines 1-11/11 (END)

**Comment by nathan30** [comment]
Could you launch the /opt/OpenCaptureForInvoices/bin/scripts/service_workerOC.sh and tell me if it return an error ?

**Comment by alexp43** [comment]
This is the return:
/opt/OpenCaptureForInvoices/bin/scripts/service_workerOC.sh : ligne 24 : 23377 Instruction non permise (core dumped) /usr/local/bin/kuyruk --app bin.src.main.OCforInvoices_worker worker --queue invoices

Thanks for your help! ;-)

**Comment by nathan30** [comment]
What is your system configuration ? proc, number of core, ram

**Comment by alexp43** [comment]
Physical machine: 
Ovh Rise-1: Intel Xeon E3-1230v6 - 4 c / 8 t - 3.5 GHz / 3.9 GHz 32Go RAM 
with proxmox
VM: 1 socket, 2 cores, 16Go RAM, IP failover with Ubuntu 20.04

**Comment by nathan30** [comment]
Could you run this and give me the return please ?

python3 -c 'import tensorflow print(tensorflow.__version__)'

**Comment by alexp43** [comment]
alex@alex-Maarch:~$ python3 -c 'import tensorflow print(tensorflow.__version__)'
  File "<string>", line 1
    import tensorflow print(tensorflow.__version__)
                      ^
SyntaxError: invalid syntax

**Comment by nathan30** [comment]
I edit the command, sorry

**Comment by alexp43** [comment]
It was maybe this, no?

alex@alex-Maarch:~$ pip show tensorflow
Name: tensorflow
Version: 2.3.1
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /usr/local/lib/python3.8/dist-packages
Requires: tensorboard, absl-py, astunparse, tensorflow-estimator, opt-einsum, numpy, protobuf, h5py, grpcio, google-pasta, keras-preprocessing, gast, termcolor, wrapt, six, wheel
Required-by:

**Comment by nathan30** [comment]
Hum, I never had this issue so I ask the creator of the Kuyruk package and here is his answer : 
https://github.com/cenkalti/kuyruk/issues/72

**Comment by alexp43** [comment]
Sorry, but I don't understand what I have to do. 
Because I didn't upgrade python, I just launched the installation script 
Can you advise me a config to test? On Debian maybe?

**Comment by nathan30** [comment]
Yes please test on a debian installation. Ubuntu wasn't tested enough, I think i will remove it from the README
