### ISSUE TITLE
HTTP Error 500 after clicking on an uploaded invoice from http://localhost/list/lot/TODAY/NEW

### ISSUE THREAD

**Issue by JulesBourdais** [edissyum/opencaptureforinvoices#26]
Hi,
So I installed locally following your setup guide. It seems to be working just fine, then I uploaded an invoice and it works well. But when I visit this URL http://localhost/list/lot/TODAY/NEW and click on my freshly uploaded invoice, I get a HTTP Error 500.
![Screenshot from 2020-12-22 10-48-16](https://user-images.githubusercontent.com/76167278/102874879-571dcb00-4443-11eb-90ea-790e277a182f.png)
![Screenshot from 2020-12-22 10-50-08](https://user-images.githubusercontent.com/76167278/102875015-86ccd300-4443-11eb-9fac-80c793186219.png)

By the way the invoice is a regular PDF file.

I would really appreciate some help on this.

Kind regards

Edit : I'm on Ubuntu 20.04

**Comment by nathan30** [comment]
Hi,

Could you reproduce the problem and then launch the following command : 

`tail -f /opt/OpenCaptureForInvoices/bin/data/log/OCForInvoices.log`
`sudo systemctl status OCForInvoices-web`
`sudo systemctl status OCForInvoices-worker`

**Comment by JulesBourdais** [comment]
![image](https://user-images.githubusercontent.com/76167278/102883107-be417c80-444f-11eb-8f5a-3b4b423b655b.png)
![image](https://user-images.githubusercontent.com/76167278/102883166-d5806a00-444f-11eb-930b-c5837f7b2c65.png)
![image](https://user-images.githubusercontent.com/76167278/102883216-f0eb7500-444f-11eb-9713-5c5de8085d34.png)

**Comment by nathan30** [comment]
The xlrd error is showing up at the moment you have the error 500 ?

**Comment by JulesBourdais** [comment]
Yes absolutely ! Here is the complete log :
![image](https://user-images.githubusercontent.com/76167278/102898042-38cac600-4469-11eb-97f8-3cc39ca6a960.png)

Ty for you help

**Comment by nathan30** [comment]
Okay, the issue is caused by the xlrd package version. I'll push a fix soon to stop the use of this package. If you don't want to wait : 

`sudo pip3 install xlrd==1.2.0`

**Comment by JulesBourdais** [comment]
Okay, thank you. It's working fine now.
Have a nice day
