### ISSUE TITLE
Is it possible to detect custom values ?

### ISSUE THREAD

**Issue by JulesBourdais** [edissyum/opencaptureforinvoices#27]
Hi again,
I have a question which is not related to a bug.
I'm working with a customer who is processing health data.
They got "invoices" like this one :
![pullrequest2](https://user-images.githubusercontent.com/76167278/102906614-2a82a700-4475-11eb-8820-ae958759b0f5.png)
Is it possible to detect the values in the columns like 'Patient' or 'Numéro SS' with Opencaptureforinvoices ?
I saw we can target certains fields with regex, but because I got peculiar invoices I think I need to position a mask, but I did not find anything relevant to my situation in the README.

So, is it possible to achieve this ?
Regards

**Comment by nathan30** [comment]
I'm currently writing a tutorial and a more detailled instructions here : https://edissyum.gitbook.io/open-capture-for-invoices/ 

You'll find a lot more informations than the readme

By the way for your problem, you need informations into an array. For now, Open-Capture For Invoices doesn't not handle data from an array. But this is a feature that we will implemented in the future

**Comment by JulesBourdais** [comment]
Ok, I will definitely take a look.
Do you have a roadmap for the implementation of new features like data from array handling ?
Do you think it is possible to get around this limitation (data from array), for instance by processing only one line of the array at once, and create one mask for each row ?
Thanks a lot :)

**Comment by nathan30** [comment]
The roadmap will be out soon :) 

You could process it by position with mask, but if you have X lines in invoice A and Y lines in invoice B, you'll have trouble. The easy way, I think, is to REGEX the data you want (easy for SS number) and then process them as you want
