### ISSUE TITLE
Error 500 control panel 

### ISSUE THREAD

**Issue by aconte31** [edissyum/opencaptureforinvoices#74]
Hello, 

I have a problem, when i modify settings in the control panel, and i click the button modify, i have an error 500. 
I saw there was a problem quite similar but not the same unfortunately.
i will put the same log you ask for the previous problem:

tail -f /opt/OpenCaptureForInvoices/bin/data/log/OCForInvoices.log

~$ tail -f /opt/OpenCaptureForInvoices/bin/data/log/OCforInvoices.log
[Open-Capture  ] 16-03-2021 22:39:12 ERROR (401) getUsers : {"errors":"Authentication Failed"}
[Open-Capture  ] 16-03-2021 22:45:19 ERROR (401) getUsers : {"errors":"Authentication Failed"}
[Open-Capture  ] 16-03-2021 22:51:06 ERROR (401) getUsers : {"errors":"Authentication Failed"}
[Open-Capture  ] 16-03-2021 22:53:05 ERROR (401) getUsers : {"errors":"Authentication Failed"}
[Open-Capture  ] 16-03-2021 22:53:59 ERROR (401) getUsers : {"errors":"Authentication Failed"}
[Open-Capture  ] 16-03-2021 22:54:40 ERROR (401) getUsers : {"errors":"Authentication Failed"}
[Open-Capture  ] 16-03-2021 22:57:45 ERROR (401) getUsers : {"errors":"Authentication Failed"}
[Open-Capture  ] 16-03-2021 22:58:17 ERROR (401) getUsers : {"errors":"Authentication Failed"}
[Open-Capture  ] 16-03-2021 23:09:52 ERROR (401) getUsers : {"errors":"Authentication Failed"}
[Open-Capture  ] 16-03-2021 23:12:45 ERROR (401) getUsers : {"errors":"Authentication Failed"}

sudo systemctl status OCForInvoices-web:

$ sudo systemctl status OCForInvoices-web
● OCForInvoices-web.service - Gunicorn instance to Open-Capture For Invoices
   Loaded: loaded (/etc/systemd/system/OCForInvoices-web.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2021-03-16 23:12:36 CET; 1 months 12 days ago
 Main PID: 11516 (gunicorn)
    Tasks: 5 (limit: 4915)
   Memory: 228.5M
   CGroup: /system.slice/OCForInvoices-web.service
           ├─11516 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 --workers 3 --bind unix:OCForInvoices.sock -m 007 w
           ├─11519 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 --workers 3 --bind unix:OCForInvoices.sock -m 007 w
           ├─11520 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 --workers 3 --bind unix:OCForInvoices.sock -m 007 w
           └─11521 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 --workers 3 --bind unix:OCForInvoices.sock -m 007 w

avril 29 09:56:57 testged gunicorn[11516]:     return view(**kwargs)
avril 29 09:56:57 testged gunicorn[11516]:   File "/opt/OpenCaptureForInvoices/webApp/ws.py", line 77, in update_config
avril 29 09:56:57 testged gunicorn[11516]:     if dashboard.modify_config(request.form):
avril 29 09:56:57 testged gunicorn[11516]:   File "/opt/OpenCaptureForInvoices/webApp/dashboard.py", line 181, in modify_config
avril 29 09:56:57 testged gunicorn[11516]:     parser.set(section, field, data[info])
avril 29 09:56:57 testged gunicorn[11516]:   File "/usr/lib/python3.7/configparser.py", line 1198, in set
avril 29 09:56:57 testged gunicorn[11516]:     super().set(section, option, value)
avril 29 09:56:57 testged gunicorn[11516]:   File "/usr/lib/python3.7/configparser.py", line 900, in set
avril 29 09:56:57 testged gunicorn[11516]:     raise NoSectionError(section) from None
avril 29 09:56:57 testged gunicorn[11516]: configparser.NoSectionError: No section: 'REMOVEBLANKPAGES

$ sudo systemctl status OCForInvoices-worker

● OCForInvoices-worker.service - Daemon for Open-Capture for Invoices
   Loaded: loaded (/etc/systemd/system/OCForInvoices-worker.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2021-04-29 10:06:59 CEST; 1s ago
  Process: 25852 ExecStart=/opt/OpenCaptureForInvoices//bin/scripts/service_workerOC.sh (code=exited, status=216/GROUP)
 Main PID: 25852 (code=exited, status=216/GROUP)

avril 29 10:06:59 testged systemd[1]: OCForInvoices-worker.service: Service RestartSec=100ms expired, scheduling restart.
avril 29 10:06:59 testged systemd[1]: OCForInvoices-worker.service: Scheduled restart job, restart counter is at 5.
avril 29 10:06:59 testged systemd[1]: Stopped Daemon for Open-Capture for Invoices.
avril 29 10:06:59 testged systemd[1]: OCForInvoices-worker.service: Start request repeated too quickly.
avril 29 10:06:59 testged systemd[1]: OCForInvoices-worker.service: Failed with result 'exit-code'.
avril 29 10:06:59 testged systemd[1]: Failed to start Daemon for Open-Capture for Invoices.

i will add an extra log from cmd $ sudo journalctl -xe
-- The unit OCForInvoices-worker.service has entered the 'failed' state with result 'exit-code'.
avril 29 10:06:59 testged systemd[1]: OCForInvoices-worker.service: Service RestartSec=100ms expired, scheduling restart.
avril 29 10:06:59 testged systemd[1]: OCForInvoices-worker.service: Scheduled restart job, restart counter is at 5.
-- Subject: Le redémarrage automatique d'une unité (unit) a été planifié
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Le redémarrage automatique de l'unité (unit) OCForInvoices-worker.service a été planifié, en
-- raison de sa configuration avec le paramètre Restart=.
avril 29 10:06:59 testged systemd[1]: Stopped Daemon for Open-Capture for Invoices.
-- Subject: L'unité (unit) OCForInvoices-worker.service a terminé son arrêt
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- L'unité (unit) OCForInvoices-worker.service a terminé son arrêt.
avril 29 10:06:59 testged systemd[1]: OCForInvoices-worker.service: Start request repeated too quickly.
avril 29 10:06:59 testged systemd[1]: OCForInvoices-worker.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- The unit OCForInvoices-worker.service has entered the 'failed' state with result 'exit-code'.
avril 29 10:06:59 testged systemd[1]: Failed to start Daemon for Open-Capture for Invoices.
-- Subject: L'unité (unit) OCForInvoices-worker.service a échoué
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- L'unité (unit) OCForInvoices-worker.service a échoué, avec le résultat failed.
avril 29 10:07:01 testged sudo[25853]:   aconte : TTY=pts/1 ; PWD=/opt/OpenCaptureForInvoices/bin/data/log/Supervisor ; USER=roo
avril 29 10:07:01 testged sudo[25853]: pam_unix(sudo:session): session opened for user root by aconte(uid=0)
avril 29 10:07:01 testged sudo[25853]: pam_unix(sudo:session): session closed for user root
avril 29 10:07:26 testged sudo[25864]:   aconte : TTY=pts/1 ; PWD=/opt/OpenCaptureForInvoices/bin/data/log/Supervisor ; USER=roo
avril 29 10:07:26 testged sudo[25864]: pam_unix(sudo:session): session opened for user root by aconte(uid=0)

My regards, Aconte.

**Comment by aconte31** [comment]
i manage to make the ocfi-worker.service working by editing the .service file.

sudo systemctl status -l OCForInvoices-worker.service

● OCForInvoices-worker.service - Daemon for Open-Capture for Invoices
   Loaded: loaded (/etc/systemd/system/OCForInvoices-worker.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2021-04-29 10:33:50 CEST; 3s ago
 Main PID: 27713 (service_workerO)
    Tasks: 3 (limit: 4915)
   Memory: 157.6M
   CGroup: /system.slice/OCForInvoices-worker.service
           ├─27713 /bin/bash /opt/OpenCaptureForInvoices/bin/scripts/service_workerOC.sh
           └─27714 /usr/bin/python3 /usr/local/bin/kuyruk --app bin.src.main.OCforInvoices_worker worker --queue invoices

avril 29 10:33:50 testged systemd[1]: Started Daemon for Open-Capture for Invoices.
avril 29 10:33:52 testged service_workerOC.sh[27713]: I kuyruk.kuyruk.connection:85 - Connected to RabbitMQ
avril 29 10:33:52 testged service_workerOC.sh[27713]: I kuyruk.kuyruk.channel:60 - Opened new channel
avril 29 10:33:52 testged service_workerOC.sh[27713]: I kuyruk.worker._consume_messages:139 - Consumer started
avril 29 10:33:52 testged service_workerOC.sh[27713]: I kuyruk.kuyruk.connection:85 - Connected to RabbitMQ
avril 29 10:33:52 testged service_workerOC.sh[27713]: I kuyruk.kuyruk.channel:60 - Opened new channel

But it did not resolve my internal 500 error when i try to modify the settings

**Comment by nathan30** [comment]
Hi,

Which version of Open-Capture do you use ?

From what I see, you update the version but there is an issue in the config file. 

I need to update the wiki for that. Indeed, when you update the application, you need to check if the config file of the new version doesn't have new (or modify) parameters.

For the Authentification Failed error in the log, did you enabled the GED in the config file ?

**Comment by aconte31** [comment]
I am using:
Version actuelle : 0.7.5

After i manage to make the .service working, i try to see what the cmd journalctl -xe, here it is:

avril 29 10:34:39 testged gunicorn[11516]:     return cors_after_request(app.make_response(f(*args, **kwargs)))
avril 29 10:34:39 testged gunicorn[11516]:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1821, in handle_us
avril 29 10:34:39 testged gunicorn[11516]:     reraise(exc_type, exc_value, tb)
avril 29 10:34:39 testged gunicorn[11516]:   File "/usr/local/lib/python3.7/dist-packages/flask/_compat.py", line 39, in reraise
avril 29 10:34:39 testged gunicorn[11516]:     raise value
avril 29 10:34:39 testged gunicorn[11516]:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_disp
avril 29 10:34:39 testged gunicorn[11516]:     rv = self.dispatch_request()
avril 29 10:34:39 testged gunicorn[11516]:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_
avril 29 10:34:39 testged gunicorn[11516]:     return self.view_functions[rule.endpoint](**req.view_args)
avril 29 10:34:39 testged gunicorn[11516]:   File "/opt/OpenCaptureForInvoices/webApp/auth.py", line 137, in wrapped_view
avril 29 10:34:39 testged gunicorn[11516]:     return view(**kwargs)
avril 29 10:34:39 testged gunicorn[11516]:   File "/opt/OpenCaptureForInvoices/webApp/ws.py", line 77, in update_config
avril 29 10:34:39 testged gunicorn[11516]:     if dashboard.modify_config(request.form):
avril 29 10:34:39 testged gunicorn[11516]:   File "/opt/OpenCaptureForInvoices/webApp/dashboard.py", line 181, in modify_config
avril 29 10:34:39 testged gunicorn[11516]:     parser.set(section, field, data[info])
avril 29 10:34:39 testged gunicorn[11516]:   File "/usr/lib/python3.7/configparser.py", line 1198, in set
avril 29 10:34:39 testged gunicorn[11516]:     super().set(section, option, value)
avril 29 10:34:39 testged gunicorn[11516]:   File "/usr/lib/python3.7/configparser.py", line 900, in set
avril 29 10:34:39 testged gunicorn[11516]:     raise NoSectionError(section) from None
avril 29 10:34:39 testged gunicorn[11516]: configparser.NoSectionError: No section: 'REMOVEBLANKPAGES'
avril 29 10:34:50 testged xe-daemon[904]: Running CollectOS ...
avril 29 10:34:50 testged xe-daemon[904]: Running CollectMisc ...
avril 29 10:34:50 testged xe-daemon[904]: Running CollectNetworkAddr ...
avril 29 10:34:50 testged xe-daemon[904]: Running CollectDisk ...
avril 29 10:34:51 testged xe-daemon[904]: Running CollectMemory ...
avril 29 10:35:01 testged CRON[27978]: pam_unix(cron:session): session opened for user maarch by (uid=0)
avril 29 10:35:01 testged CRON[27979]: pam_unix(cron:session): session opened for user maarch by (uid=0)
avril 29 10:35:01 testged CRON[27980]: (maarch) CMD (/var/www/html/MaarchCourrier/custom/cs_linagora2/modules/full_text/scripts/
avril 29 10:35:01 testged CRON[27981]: (maarch) CMD (/var/www/html/MaarchCourrier/custom/cs_linagora/modules/full_text/scripts/l
avril 29 10:35:01 testged CRON[27979]: pam_unix(cron:session): session closed for user maarch
avril 29 10:35:01 testged CRON[27978]: pam_unix(cron:session): session closed for user maarch
avril 29 10:35:03 testged sudo[27988]:   aconte : TTY=pts/1 ; PWD=/opt/OpenCaptureForInvoices/bin/data/log/Supervisor ; USER=roo
avril 29 10:35:03 testged sudo[27988]: pam_unix(sudo:session): session opened for user root by aconte(uid=0)

For the Authentification Failed error in the log, did you enabled the GED in the config file ?
No i did not but i 'am not the only one using it so i will ask my colleague if he tried to modify the GED in the config file.

**Comment by nathan30** [comment]
Could you send me your config file and the following file please ?

webApp/templates/dashboard/index.html

**Comment by aconte31** [comment]
which one do you need ? 

/opt/OpenCaptureForInvoices/.git/config
/opt/OpenCaptureForInvoices/instance/config.ini
/opt/OpenCaptureForInvoices/instance/config
/opt/OpenCaptureForInvoices/instance/config/config_DEFAULT.ini
/opt/OpenCaptureForInvoices/instance/config/config_DEFAULT.ini.default
/opt/OpenCaptureForInvoices/instance/config.ini.default

**Comment by nathan30** [comment]
This one  /opt/OpenCaptureForInvoices/instance/config/config_DEFAULT.ini

**Comment by aconte31** [comment]
here they are:
[files.zip](https://github.com/edissyum/opencaptureforinvoices/files/6397395/files.zip)

**Comment by nathan30** [comment]
Ok, there is a fix for that in the 0.8.3 version 

You could update the application (caution with config file after the update and also the database (there is some changes in the 0.7.6) or just report the fixes if you do not want to update the version

The fix is, in the  `webApp/templates/dashboard/index.html` file : 

Replace all the `REMOVEBLANKPAGES` by `REMOVE-BLANK-PAGES`

Normally it would be necessary

After the update or the fix, do not forget to restart the services

**Comment by aconte31** [comment]
Thank you so i will update opencapture is it better to update to the last version directly the 1.0.0 .

And last question to update, is there a documentation to update, i found any. 

Best regards.

**Comment by nathan30** [comment]
There is not, for now. In the last version there is an update script to makes it easier. I'll need to [update the wiki ](https://edissyum.gitbook.io/open-capture-for-invoices/)to include the procedure.

Awaiting that here is what you can do : 

- Backup your OpenCapture folder
- Then go to your original OpenCapture folder
- Remove any modifications (will not remove your config file) : `git stash`
- Retrieve last tags : `git pull`
- Switch to last tag : `git checkout 1.0.0`
- Remove git mandatory files : `find -name '.gitkeep' -delete`
- Fix rights for scripts : `chmod u+x bin/scripts/*.sh`
- If you can, drop your current database and recreate a new one using the last structure. If you can't, please check new columns name and makes the modification into your database
- Check if there is new parameters in the `instance/config/config_DEFAULT.ini.default{`file
- Restart all the services and check if there is no error

I think I didn't forget anything

**Comment by aconte31** [comment]
Thank you again, for now i just fixed the error and it is working fine. I'll try to update in the future. 

My best regards. :)

**Comment by aconte31** [comment]
Hello,

I have done the update to the 1.0.3 normally i restarted the services and when I want to go in the dashboard or supplier list i got an 500 error again.

Regards. 

P.S: For the database since we did not use it yet, i did not found tables on Postgres. And for the config_DEFAULT.ini.default how can i check that ?

**Comment by nathan30** [comment]
Hi,

Could you send me the return of `sudo systemctl status -l OCForInvoices-web.service` ?

**Comment by aconte31** [comment]
here it is:

sudo systemctl status -l OCForInvoices-web.service
● OCForInvoices-web.service - Gunicorn instance to Open-Capture For Invoices
   Loaded: loaded (/etc/systemd/system/OCForInvoices-web.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-07-28 14:59:54 CEST; 45min ago
 Main PID: 3835 (gunicorn)
    Tasks: 8 (limit: 4915)
   Memory: 232.4M
   CGroup: /system.slice/OCForInvoices-web.service
           ├─3835 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 --workers 3 --bind unix:OCForInvoices.sock -m 007 wsgi:appw
           ├─3838 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 --workers 3 --bind unix:OCForInvoices.sock -m 007 wsgi:appw
           ├─3839 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 --workers 3 --bind unix:OCForInvoices.sock -m 007 wsgi:appw
           ├─3840 /usr/bin/python3 /usr/local/bin/gunicorn --timeout 300000 --workers 3 --bind unix:OCForInvoices.sock -m 007 wsgi:appw
           ├─4122 git cat-file --batch-check
           └─4123 git cat-file --batch

juil. 28 15:16:41 testged gunicorn[3835]:     raise value
juil. 28 15:16:41 testged gunicorn[3835]:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1950, in full_dispatch_req
juil. 28 15:16:41 testged gunicorn[3835]:     rv = self.dispatch_request()
juil. 28 15:16:41 testged gunicorn[3835]:   File "/usr/local/lib/python3.7/dist-packages/flask/app.py", line 1936, in dispatch_request
juil. 28 15:16:41 testged gunicorn[3835]:     return self.view_functions[rule.endpoint](**req.view_args)
juil. 28 15:16:41 testged gunicorn[3835]:   File "/opt/OpenCaptureForInvoices/webApp/auth.py", line 147, in wrapped_view
juil. 28 15:16:41 testged gunicorn[3835]:     return view(**kwargs)
juil. 28 15:16:41 testged gunicorn[3835]:   File "/opt/OpenCaptureForInvoices/webApp/supplier.py", line 54, in supplier_list
juil. 28 15:16:41 testged gunicorn[3835]:     })[0]['total']
juil. 28 15:16:41 testged gunicorn[3835]: TypeError: 'bool' object is not subscriptable

**Comment by nathan30** [comment]
By default, the database type used is SQLITE. Default file is located in the instance folder.

Is there any .sqlite3 file in this folder ?

**Comment by aconte31** [comment]
I have this one:
/opt/OpenCaptureForInvoices/instance/flaskr.sqlite

**Comment by nathan30** [comment]
In the config file, `databasetype` is set to pgsql or sqlite ?

**Comment by aconte31** [comment]
Here it is:
[DATABASE]
databasefile = /opt/OpenCaptureForInvoices//instance/flaskr.sqlite
databasetype = sqlite
postgreshost = localhost
postgresport = 5432
postgresdatabase = opencapture
postgresuser = 
postgrespassword =

**Comment by nathan30** [comment]
Ok, did you install Open-Capture using the Makefile ?

**Comment by aconte31** [comment]
I think i used that method but it was a long time already so i am not sure anymore, but it rings a bell in my mind.

**Comment by nathan30** [comment]
Did you use OC a lot ? If not, I think the best way is to start fresh (with the v1.0 there is a lot of changes in database and config)

If you can't, check if the sqlite file contains the structure. If not, try to launch this command, from the `webApp` folder : 

`flask init-db`

**Comment by aconte31** [comment]
I will try a fresh start since we did not use it a lot.
I tried the command just to be curious 
webApp$ flask init-db
Usage: flask [OPTIONS] COMMAND [ARGS]...
Try 'flask --help' for help.

Error: No such command 'init-db'.
